#######################################################
#                                                     #
# Makefile                                            #
#                                                     #
# Sean<SeanInApril@163.com>                           #
#                                                     #
# Usage: this file is part of project Chameleon       #
#                                                     #
#######################################################
include Makefile.inl
